name: DINACOM 2023 🚀
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Generate key
      run: php artisan key:generate
    - name: Generate Clear Cache
      run: php artisan cache:clear
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Generate Storage Link for Image
      run: php artisan storage:link
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: srv166.niagahoster.com
        username: dinacom2023@dinacom.tech
        password: dinacom2023